import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ImageBlock from "../components/site-editor-sections/ImageBlock";
import TextBlock from "../components/site-editor-sections/TextBlock";
import Heading from "../components/site-editor-sections/Heading";
import Container from "../components/site-editor-sections/Container";
import CenteredHero from "../components/site-editor-sections/CenteredHero";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}<ImageBlock />
      <TextBlock />
      <Heading />
      <Container />
      <CenteredHero />
      </body>
    </html>
  );
}
